#!/usr/bin/env python3
import fileinput
import time
import requests
import datetime
import re

user_agent = 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0'
base_sleep = 600
sleep_step = 300
counter = 0
tries_on_error = 10
debug = True
timeout = 60


def transform_outlink(url, tries, sleep):
    try:
        headers = {'user-agent':user_agent}
        response = requests.get(url, allow_redirects=True, headers=headers, timeout=timeout)
        print("response:", response)
        print("response status:", response.status_code)
        if response.status_code == 200:
            return response.url
        else:
            raise ValueError('Page responded with crawler protection')
    except:
        print('---Network / Plugin ERROR---')
        print('Transformation of', url, 'failed')

def main():
    link = "https://bs.to/out/1144412"
    print('Transforming', link,)
    print(transform_outlink(link, tries_on_error, base_sleep))

main()
